//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCar360.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORIALMANTENIMIENTO
    {
        public int Id_HistorialMantenimiento { get; set; }
        public Nullable<int> Id_MantenimientoVehiculo { get; set; }
        public Nullable<System.DateTime> HistorialMantenimiento_Fecha { get; set; }
        public string HistorialMantenimiento_Taller { get; set; }
        public Nullable<double> HistorialMantenimiento_Precio { get; set; }
        public Nullable<int> HistorialMantenimiento_Km { get; set; }
        public string HistorialMantenimiento_Comentarios { get; set; }
    
        public virtual MANTENIMIENTOVEHICULO MANTENIMIENTOVEHICULO { get; set; }

    }
}
