//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCar360.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORIALREVISIONES
    {
        public int Id_HistorialRevisiones { get; set; }
        public Nullable<int> Id_RevisionesVehiculo { get; set; }
        public System.DateTime HistorialRevisiones_Fecha { get; set; }
        public string HistorialRevisiones_Taller { get; set; }
        public Nullable<double> HistorialRevisiones_Precio { get; set; }
        public Nullable<int> HistorialRevisiones_km { get; set; }
        public string HistorialRevisiones_Comentarios { get; set; }
    
        public virtual REVISIONESVEHICULO REVISIONESVEHICULO { get; set; }
    }
}
