//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCar360.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class MANTENIMIENTOVEHICULO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MANTENIMIENTOVEHICULO()
        {
            this.HISTORIALMANTENIMIENTO = new HashSet<HISTORIALMANTENIMIENTO>();
            this.PROXIMOMANTENIMIENTO = new HashSet<PROXIMOMANTENIMIENTO>();
        }
    
        public int Id_MantenimientoVehiculo { get; set; }
        public Nullable<int> Id_Vehiculo { get; set; }
        public Nullable<int> Id_TipoMantenimiento { get; set; }
        public Nullable<int> MantenimientoVehiculo_IntervaloKm { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORIALMANTENIMIENTO> HISTORIALMANTENIMIENTO { get; set; }
        public virtual TIPOMANTENIMIENTO TIPOMANTENIMIENTO { get; set; }
        public virtual VEHICULOS VEHICULOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROXIMOMANTENIMIENTO> PROXIMOMANTENIMIENTO { get; set; }
        public int VehiculoId { get; internal set; }
    }
}
