//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCar360.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODELOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MODELOS()
        {
            this.VEHICULOS = new HashSet<VEHICULOS>();
        }
    
        public int Id_Modelo { get; set; }
        public Nullable<int> Id_Marca { get; set; }
        public Nullable<int> Id_TipoCambio { get; set; }
        public Nullable<int> Id_Etiqueta { get; set; }
        public Nullable<int> Id_Combustible { get; set; }
        public Nullable<int> Id_Carroceria { get; set; }
        public string Modelo_Nombre { get; set; }
    
        public virtual CARROCERIAS CARROCERIAS { get; set; }
        public virtual COMBUSTIBLE COMBUSTIBLE { get; set; }
        public virtual ETIQUETAS ETIQUETAS { get; set; }
        public virtual MARCAS MARCAS { get; set; }
        public virtual TIPOCAMBIO TIPOCAMBIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEHICULOS> VEHICULOS { get; set; }
    }
}
