//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCar360.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROXIMOMANTENIMIENTO
    {
        public int Id_ProximoMantenimiento { get; set; }
        public Nullable<int> Id_MantenimientoVehiculo { get; set; }
        public Nullable<int> ProximoMantenimiento_Km { get; set; }
    
        public virtual MANTENIMIENTOVEHICULO MANTENIMIENTOVEHICULO { get; set; }
    }
}
