//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCar360.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class REVISIONESVEHICULO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REVISIONESVEHICULO()
        {
            this.HISTORIALREVISIONES = new HashSet<HISTORIALREVISIONES>();
            this.PROXIMASREVISIONES = new HashSet<PROXIMASREVISIONES>();
        }
    
        public int Id_RevisionesVehiculo { get; set; }
        public Nullable<int> Id_TipoRevision { get; set; }
        public Nullable<int> Id_Vehiculo { get; set; }
        public Nullable<int> RevisionesVehiculo_Intervalokm { get; set; }
        public System.DateTime RevisionesVehiculo_IntervaloTiempo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORIALREVISIONES> HISTORIALREVISIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROXIMASREVISIONES> PROXIMASREVISIONES { get; set; }
        public virtual TIPOREVISIONES TIPOREVISIONES { get; set; }
        public virtual VEHICULOS VEHICULOS { get; set; }
    }
}
