//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCar360.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPOMANTENIMIENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPOMANTENIMIENTO()
        {
            this.MANTENIMIENTOVEHICULO = new HashSet<MANTENIMIENTOVEHICULO>();
        }
    
        public int Id_TipoMantenimiento { get; set; }
        public string Mantenimiento_Nombre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MANTENIMIENTOVEHICULO> MANTENIMIENTOVEHICULO { get; set; }
    }
}
