//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCar360.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICULOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VEHICULOS()
        {
            this.MANTENIMIENTOVEHICULO = new HashSet<MANTENIMIENTOVEHICULO>();
            this.REVISIONESVEHICULO = new HashSet<REVISIONESVEHICULO>();
        }
    
        public int Id_Vehiculo { get; set; }
        public Nullable<int> Id_Usuario { get; set; }
        public Nullable<int> Id_Modelo { get; set; }
        public Nullable<int> Id_Color { get; set; }
        public string Vehiculo_Matricula { get; set; }
        public Nullable<System.DateTime> Vehiculo_Fecha_Matriculacion { get; set; }
        public string Vehiculo_Bastidor { get; set; }
        public Nullable<int> Vehiculo_KmActuales { get; set; }
    
        public virtual COLORES COLORES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MANTENIMIENTOVEHICULO> MANTENIMIENTOVEHICULO { get; set; }
        public virtual MODELOS MODELOS { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
        public virtual USUARIOS USUARIOS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REVISIONESVEHICULO> REVISIONESVEHICULO { get; set; }
    }
}
